# Generated by Django 3.0 on 2019-12-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('deviceid', models.IntegerField(primary_key=True, serialize=False)),
                ('deviceip', models.CharField(max_length=64, unique=True)),
                ('devicename', models.CharField(max_length=64)),
                ('devicearea', models.CharField(max_length=64)),
                ('devicetype', models.CharField(max_length=64)),
                ('deviceport', models.IntegerField()),
                ('devicestat', models.BooleanField()),
                ('devicerem', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
