# Generated by Django 3.0 on 2019-12-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='deviceadt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
