# Generated by Django 3.0 on 2019-12-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0003_auto_20191222_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='deviceid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='设备序号'),
        ),
    ]
