# Generated by Django 3.0 on 2019-12-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0004_auto_20191222_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceinfo',
            options={'verbose_name': '设备列表', 'verbose_name_plural': '设备列表'},
        ),
    ]
