# Generated by Django 3.0 on 2019-12-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0006_devicecounthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecounthistory',
            name='devicecount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicecounthistory',
            name='deviceoffline',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicecounthistory',
            name='deviceonline',
            field=models.IntegerField(),
        ),
    ]
