# Generated by Django 3.0 on 2019-12-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0007_auto_20191225_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecounthistory',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
